# Netlify configuration for para-ssg
# Place this file in your repository root

[build]
  # Build command - assumes para-ssg is installed globally or available in PATH
  command = "para-ssg content/ dist/"
  
  # Directory to publish (where para-ssg outputs files)
  publish = "dist"

[build.environment]
  # Environment variables (if needed)
  RUST_BACKTRACE = "1"

# Redirects for clean URLs (optional)
[[redirects]]
  from = "/projects"
  to = "/projects/index.html"
  status = 200

[[redirects]]
  from = "/areas"
  to = "/areas/index.html"
  status = 200

[[redirects]]
  from = "/resources"
  to = "/resources/index.html"
  status = 200

[[redirects]]
  from = "/archives"
  to = "/archives/index.html"
  status = 200

# Headers for optimization
[[headers]]
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Form handling (if you add contact forms)
# [[forms]]
#   name = "contact"